ALTER TABLE public.models
    ADD COLUMN IF NOT EXISTS image_open_scale DOUBLE PRECISION DEFAULT 1,
    ADD COLUMN IF NOT EXISTS image_open_scale_x DOUBLE PRECISION DEFAULT 1,
    ADD COLUMN IF NOT EXISTS image_open_scale_y DOUBLE PRECISION DEFAULT 1,
    ADD COLUMN IF NOT EXISTS image_open_offset_x DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN IF NOT EXISTS image_open_offset_y DOUBLE PRECISION DEFAULT 0;
